# Generated by Django 6.0.4 on 2026-04-13 02:54

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA por e-mail ativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('address', models.TextField(verbose_name='endereço')),
                ('age', models.PositiveSmallIntegerField(verbose_name='idade')),
                ('religion', models.CharField(choices=[('muculmano', 'Muçulmano'), ('judeu', 'Judeu'), ('catolico', 'Católico')], max_length=20, verbose_name='religião')),
                ('political_ideology', models.CharField(choices=[('esquerda', 'Esquerda'), ('direita', 'Direita'), ('centro', 'Centro')], max_length=20, verbose_name='ideologia política')),
                ('profession', models.CharField(max_length=255, verbose_name='profissão')),
                ('number_of_children', models.PositiveSmallIntegerField(default=0, verbose_name='número de filhos')),
                ('income_before_war', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='renda familiar antes da guerra')),
                ('education', models.CharField(choices=[('fundamental', 'Ensino fundamental'), ('medio', 'Ensino médio'), ('superior', 'Ensino superior'), ('pos', 'Pós-graduação')], max_length=20, verbose_name='maior grau de formação escolar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refugee', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'refugee',
                'verbose_name_plural': 'refugees',
            },
        ),
    ]
